name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        platform: [windows-2019, windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - run: wsl --help
